/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'date' : string,
  'name' : string,
  'description' : string,
  'image' : [] | [string],
  'location' : string,
}
export type EventId = bigint;
export interface Person {
  'bio' : string,
  'eventId' : EventId,
  'name' : string,
  'role' : PersonRole,
  'photoUrl' : string,
}
export type PersonId = bigint;
export type PersonRole = { 'celebrity' : null } |
  { 'speaker' : null };
export interface Ticket {
  'eventId' : EventId,
  'attendeeName' : string,
  'email' : string,
}
export type TicketId = bigint;
export interface TimetableEntry {
  'eventId' : EventId,
  'topic' : string,
  'time' : string,
  'speakerName' : [] | [string],
}
export type TimetableId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<[Event], EventId>,
  'createPerson' : ActorMethod<[Person], PersonId>,
  'createTimetableEntry' : ActorMethod<[TimetableEntry], TimetableId>,
  'deleteEvent' : ActorMethod<[EventId], undefined>,
  'deletePerson' : ActorMethod<[PersonId], undefined>,
  'deleteTimetableEntry' : ActorMethod<[TimetableId], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAttendeeCount' : ActorMethod<[EventId], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[EventId], Event>,
  'getPeopleByEvent' : ActorMethod<[EventId], Array<Person>>,
  'getTicketsByEvent' : ActorMethod<[EventId], Array<Ticket>>,
  'getTimetableByEvent' : ActorMethod<[EventId], Array<TimetableEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerTicket' : ActorMethod<[Ticket], TicketId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEvent' : ActorMethod<[EventId, Event], undefined>,
  'updatePerson' : ActorMethod<[PersonId, Person], undefined>,
  'updateTimetableEntry' : ActorMethod<
    [TimetableId, TimetableEntry],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];