/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const EventId = IDL.Nat;
export const PersonRole = IDL.Variant({
  'celebrity' : IDL.Null,
  'speaker' : IDL.Null,
});
export const Person = IDL.Record({
  'bio' : IDL.Text,
  'eventId' : EventId,
  'name' : IDL.Text,
  'role' : PersonRole,
  'photoUrl' : IDL.Text,
});
export const PersonId = IDL.Nat;
export const TimetableEntry = IDL.Record({
  'eventId' : EventId,
  'topic' : IDL.Text,
  'time' : IDL.Text,
  'speakerName' : IDL.Opt(IDL.Text),
});
export const TimetableId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Ticket = IDL.Record({
  'eventId' : EventId,
  'attendeeName' : IDL.Text,
  'email' : IDL.Text,
});
export const TicketId = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func([Event], [EventId], []),
  'createPerson' : IDL.Func([Person], [PersonId], []),
  'createTimetableEntry' : IDL.Func([TimetableEntry], [TimetableId], []),
  'deleteEvent' : IDL.Func([EventId], [], []),
  'deletePerson' : IDL.Func([PersonId], [], []),
  'deleteTimetableEntry' : IDL.Func([TimetableId], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAttendeeCount' : IDL.Func([EventId], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([EventId], [Event], ['query']),
  'getPeopleByEvent' : IDL.Func([EventId], [IDL.Vec(Person)], ['query']),
  'getTicketsByEvent' : IDL.Func([EventId], [IDL.Vec(Ticket)], ['query']),
  'getTimetableByEvent' : IDL.Func(
      [EventId],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerTicket' : IDL.Func([Ticket], [TicketId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEvent' : IDL.Func([EventId, Event], [], []),
  'updatePerson' : IDL.Func([PersonId, Person], [], []),
  'updateTimetableEntry' : IDL.Func([TimetableId, TimetableEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const EventId = IDL.Nat;
  const PersonRole = IDL.Variant({
    'celebrity' : IDL.Null,
    'speaker' : IDL.Null,
  });
  const Person = IDL.Record({
    'bio' : IDL.Text,
    'eventId' : EventId,
    'name' : IDL.Text,
    'role' : PersonRole,
    'photoUrl' : IDL.Text,
  });
  const PersonId = IDL.Nat;
  const TimetableEntry = IDL.Record({
    'eventId' : EventId,
    'topic' : IDL.Text,
    'time' : IDL.Text,
    'speakerName' : IDL.Opt(IDL.Text),
  });
  const TimetableId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Ticket = IDL.Record({
    'eventId' : EventId,
    'attendeeName' : IDL.Text,
    'email' : IDL.Text,
  });
  const TicketId = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func([Event], [EventId], []),
    'createPerson' : IDL.Func([Person], [PersonId], []),
    'createTimetableEntry' : IDL.Func([TimetableEntry], [TimetableId], []),
    'deleteEvent' : IDL.Func([EventId], [], []),
    'deletePerson' : IDL.Func([PersonId], [], []),
    'deleteTimetableEntry' : IDL.Func([TimetableId], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAttendeeCount' : IDL.Func([EventId], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([EventId], [Event], ['query']),
    'getPeopleByEvent' : IDL.Func([EventId], [IDL.Vec(Person)], ['query']),
    'getTicketsByEvent' : IDL.Func([EventId], [IDL.Vec(Ticket)], ['query']),
    'getTimetableByEvent' : IDL.Func(
        [EventId],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerTicket' : IDL.Func([Ticket], [TicketId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEvent' : IDL.Func([EventId, Event], [], []),
    'updatePerson' : IDL.Func([PersonId, Person], [], []),
    'updateTimetableEntry' : IDL.Func([TimetableId, TimetableEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };