/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type EventId = bigint;
export type TimetableId = bigint;
export interface Event {
    date: string;
    name: string;
    description: string;
    image?: string;
    location: string;
}
export interface TimetableEntry {
    eventId: EventId;
    topic: string;
    time: string;
    speakerName?: string;
}
export interface Ticket {
    eventId: EventId;
    attendeeName: string;
    email: string;
}
export type PersonId = bigint;
export type TicketId = bigint;
export interface UserProfile {
    name: string;
}
export interface Person {
    bio: string;
    eventId: EventId;
    name: string;
    role: PersonRole;
    photoUrl: string;
}
export enum PersonRole {
    celebrity = "celebrity",
    speaker = "speaker"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEvent(event: Event): Promise<EventId>;
    createPerson(person: Person): Promise<PersonId>;
    createTimetableEntry(entry: TimetableEntry): Promise<TimetableId>;
    deleteEvent(id: EventId): Promise<void>;
    deletePerson(id: PersonId): Promise<void>;
    deleteTimetableEntry(id: TimetableId): Promise<void>;
    getAllEvents(): Promise<Array<Event>>;
    getAttendeeCount(eventId: EventId): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEvent(id: EventId): Promise<Event>;
    getPeopleByEvent(eventId: EventId): Promise<Array<Person>>;
    getTicketsByEvent(eventId: EventId): Promise<Array<Ticket>>;
    getTimetableByEvent(eventId: EventId): Promise<Array<TimetableEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerTicket(ticket: Ticket): Promise<TicketId>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEvent(id: EventId, event: Event): Promise<void>;
    updatePerson(id: PersonId, person: Person): Promise<void>;
    updateTimetableEntry(id: TimetableId, entry: TimetableEntry): Promise<void>;
}
import type { Event as _Event, EventId as _EventId, Person as _Person, PersonRole as _PersonRole, TimetableEntry as _TimetableEntry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: Event): Promise<EventId> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_Event_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_Event_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPerson(arg0: Person): Promise<PersonId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPerson(to_candid_Person_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPerson(to_candid_Person_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTimetableEntry(arg0: TimetableEntry): Promise<TimetableId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTimetableEntry(to_candid_TimetableEntry_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTimetableEntry(to_candid_TimetableEntry_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteEvent(arg0: EventId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deletePerson(arg0: PersonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePerson(arg0);
            return result;
        }
    }
    async deleteTimetableEntry(arg0: TimetableId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTimetableEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTimetableEntry(arg0);
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendeeCount(arg0: EventId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendeeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendeeCount(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: EventId): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_Event_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_Event_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPeopleByEvent(arg0: EventId): Promise<Array<Person>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPeopleByEvent(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPeopleByEvent(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicketsByEvent(arg0: EventId): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketsByEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketsByEvent(arg0);
            return result;
        }
    }
    async getTimetableByEvent(arg0: EventId): Promise<Array<TimetableEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimetableByEvent(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimetableByEvent(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerTicket(arg0: Ticket): Promise<TicketId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTicket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTicket(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateEvent(arg0: EventId, arg1: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, to_candid_Event_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, to_candid_Event_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePerson(arg0: PersonId, arg1: Person): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerson(arg0, to_candid_Person_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerson(arg0, to_candid_Person_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTimetableEntry(arg0: TimetableId, arg1: TimetableEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimetableEntry(arg0, to_candid_TimetableEntry_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimetableEntry(arg0, to_candid_TimetableEntry_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Event_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PersonRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonRole): PersonRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Person_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Person): Person {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TimetableEntry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimetableEntry): TimetableEntry {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    name: string;
    description: string;
    image: [] | [string];
    location: string;
}): {
    date: string;
    name: string;
    description: string;
    image?: string;
    location: string;
} {
    return {
        date: value.date,
        name: value.name,
        description: value.description,
        image: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.image)),
        location: value.location
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    eventId: _EventId;
    name: string;
    role: _PersonRole;
    photoUrl: string;
}): {
    bio: string;
    eventId: EventId;
    name: string;
    role: PersonRole;
    photoUrl: string;
} {
    return {
        bio: value.bio,
        eventId: value.eventId,
        name: value.name,
        role: from_candid_PersonRole_n21(_uploadFile, _downloadFile, value.role),
        photoUrl: value.photoUrl
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventId: _EventId;
    topic: string;
    time: string;
    speakerName: [] | [string];
}): {
    eventId: EventId;
    topic: string;
    time: string;
    speakerName?: string;
} {
    return {
        eventId: value.eventId,
        topic: value.topic,
        time: value.time,
        speakerName: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.speakerName))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    celebrity: null;
} | {
    speaker: null;
}): PersonRole {
    return "celebrity" in value ? PersonRole.celebrity : "speaker" in value ? PersonRole.speaker : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Person>): Array<Person> {
    return value.map((x)=>from_candid_Person_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimetableEntry>): Array<TimetableEntry> {
    return value.map((x)=>from_candid_TimetableEntry_n24(_uploadFile, _downloadFile, x));
}
function to_candid_Event_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): _Event {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PersonRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonRole): _PersonRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Person_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Person): _Person {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TimetableEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimetableEntry): _TimetableEntry {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventId: EventId;
    topic: string;
    time: string;
    speakerName?: string;
}): {
    eventId: _EventId;
    topic: string;
    time: string;
    speakerName: [] | [string];
} {
    return {
        eventId: value.eventId,
        topic: value.topic,
        time: value.time,
        speakerName: value.speakerName ? candid_some(value.speakerName) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    name: string;
    description: string;
    image?: string;
    location: string;
}): {
    date: string;
    name: string;
    description: string;
    image: [] | [string];
    location: string;
} {
    return {
        date: value.date,
        name: value.name,
        description: value.description,
        image: value.image ? candid_some(value.image) : candid_none(),
        location: value.location
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    eventId: EventId;
    name: string;
    role: PersonRole;
    photoUrl: string;
}): {
    bio: string;
    eventId: _EventId;
    name: string;
    role: _PersonRole;
    photoUrl: string;
} {
    return {
        bio: value.bio,
        eventId: value.eventId,
        name: value.name,
        role: to_candid_PersonRole_n7(_uploadFile, _downloadFile, value.role),
        photoUrl: value.photoUrl
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonRole): {
    celebrity: null;
} | {
    speaker: null;
} {
    return value == PersonRole.celebrity ? {
        celebrity: null
    } : value == PersonRole.speaker ? {
        speaker: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
